### ISSUE TITLE
NPE while calling vector.analogyWords in Word2VecExample

### ISSUE THREAD

**Issue by pbadenski** [SkymindIO/deeplearning4j#109]
Version: 0.0.3.2.6
Type of Neural Net: Word2Vec
Configuration: see Word2VecExample
Data: contents of http://www.axonframework.org/docs/2.3/single.html
Description of problem: I get an NPE for calling "vec.analogyWords" with any combinations of words (words to exist in the vocabulary).
Stack trace:

    Exception in thread "main" java.lang.NullPointerException
    	at org.deeplearning4j.models.word2vec.Word2Vec.analogy(Word2Vec.java:387)
    	at org.deeplearning4j.models.word2vec.Word2Vec.analogyWords(Word2Vec.java:206)
    	at org.deeplearning4j.word2vec.Word2VecExample.train(Word2VecExample.java:91)
    	at org.deeplearning4j.word2vec.Word2VecExample.main(Word2VecExample.java:35)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Root cause (hypothesis):
I noticed that during the *InMemoryLookupCache* initialization the *wordIndex* has *objects* and *indexes* map of a different size. Further investigation showed that values of *indexes* map contain duplicates. I had a look at the *VocabActor* class and noticed this part of code:

    int idx = cache.numWords();
    token2.setIndex(idx);
    cache.putVocabWord(token);
I believe that this part is not thread-safe and causes the issue.

**Comment by agibsonccc** [comment]
Analogy no longer exists in trunk. Open another issue if this happens with the new wordsNearest. Thanks!

**Comment by pbadenski** [comment]
It might not be, but I still think there's a problem with thread-safety with VocabActor. Have a look at root cause explanation of NPE.
