### ISSUE TITLE
AssertionFailure in testDbn() from StackedDenoisingAutoEncoderTest 

### ISSUE THREAD

**Issue by delip** [SkymindIO/deeplearning4j#112]
java.lang.AssertionError: Found infinite or nan
at org.nd4j.linalg.util.LinAlgExceptions.assertValidNum(LinAlgExceptions.java:39)
at org.deeplearning4j.nn.BaseMultiLayerNetwork.computeDeltasR(BaseMultiLayerNetwork.java:493)
at org.deeplearning4j.nn.BaseMultiLayerNetwork.backPropGradientR(BaseMultiLayerNetwork.java:1192)
at org.deeplearning4j.nn.BaseMultiLayerNetwork.getBackPropRGradient(BaseMultiLayerNetwork.java:756)
at org.deeplearning4j.optimize.solvers.StochasticHessianFree.conjGradient(StochasticHessianFree.java:110)
at org.deeplearning4j.optimize.solvers.StochasticHessianFree.runConjugateGradient(StochasticHessianFree.java:154)
at org.deeplearning4j.optimize.solvers.StochasticHessianFree.optimize(StochasticHessianFree.java:259)
at org.deeplearning4j.optimize.optimizers.BackPropOptimizer.lineSearchBackProp(BackPropOptimizer.java:74)
at org.deeplearning4j.optimize.optimizers.BackPropOptimizer.optimize(BackPropOptimizer.java:48)
at org.deeplearning4j.nn.BaseMultiLayerNetwork.backProp(BaseMultiLayerNetwork.java:857)
at org.deeplearning4j.optimize.optimizers.MultiLayerNetworkOptimizer.optimize(MultiLayerNetworkOptimizer.java:47)
at org.deeplearning4j.optimize.optimizers.MultiLayerNetworkOptimizer.optimize(MultiLayerNetworkOptimizer.java:55)
at org.deeplearning4j.nn.BaseMultiLayerNetwork.finetune(BaseMultiLayerNetwork.java:1289)
at org.deeplearning4j.nn.BaseMultiLayerNetwork.fit(BaseMultiLayerNetwork.java:1349)
at org.deeplearning4j.nn.BaseMultiLayerNetwork.fit(BaseMultiLayerNetwork.java:1359)
at org.deeplearning4j.models.classifiers.sda.StackedDenoisingAutoEncoderTest.testDbn(StackedDenoisingAutoEncoderTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by agibsonccc** [comment]
Test no longer exists.
