### ISSUE TITLE
Test IRUnitSVMLightWorkerTest.testLearnIrisFunctionViaIRNN_MLP fails with an NPE

### ISSUE THREAD

**Issue by smarthi** [SkymindIO/deeplearning4j#139]
Here's the stacktrace:

{Code}

testLearnIrisFunctionViaIRNN_MLP(org.deeplearning4j.iterativereduce.impl.multilayer.IRUnitSVMLightWorkerTest)  Time elapsed: 1.339 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:303)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initializeLayers(MultiLayerNetwork.java:269)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setInput(MultiLayerNetwork.java:1313)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:174)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1077)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1104)
	at org.deeplearning4j.iterativereduce.impl.multilayer.WorkerNode.compute(WorkerNode.java:71)
	at org.deeplearning4j.iterativereduce.impl.multilayer.WorkerNode.compute(WorkerNode.java:32)
	at org.deeplearning4j.iterativereduce.irunit.IRUnitDriver.simulateRun(IRUnitDriver.java:228)
	at org.deeplearning4j.iterativereduce.impl.multilayer.IRUnitSVMLightWorkerTest.testLearnIrisFunctionViaIRNN_MLP(IRUnitSVMLightWorkerTest.java:38)

{Code}

**Comment by jpatanooga** [comment]
well. the IRUnit test runs worked when I first committed them.

That means Adam broke em!

=D

**Comment by smarthi** [comment]
Seems like It.  The  configuration is not being passed to the driver, could have to do with the switch to Canova configuration that Adam committed yesterday

**Comment by agibsonccc** [comment]
Heh. Something to do with the app input path not being resolved on the iterative reduce configuration.  I added class path resolution for the properties and it works fine, but now has trouble finding the data. Shouldn't be a hard fix, just need to poke around with the directory structure a bit.

It's not resolving the proper absolute path for the file and fails to load causing the null pointer.

**Comment by smarthi** [comment]
Agreed, that's what I noticed too locally but didn't have the time to poke
around to fix it. Should be a trivial fix thou.

**Comment by smarthi** [comment]
Ok, I think I fixed it, will send a PR out later tonight.

**Comment by agibsonccc** [comment]
I'll be curious to see if your fix is cleaner than mine. Feel free to submit it. I managed to hook it up this morning though. Looking forward to comparing notes.

**Comment by smarthi** [comment]
There was an old reference to
org.deeplearning4j.hadoop.yarn.models.featuredetectors.rbm.RBM in the test
properties file.

Changed that to org.deeplearning4j.models.featuredetectors.rbm.RBM and that
fixed it.

The former does not exist anymore. Is that all there is to it?

**Comment by agibsonccc** [comment]
There was going to be another bug after that which involved the absolute path resolution of the input files. I fixed that as well.

**Comment by smarthi** [comment]
yeah I am hitting the other bug now in a Spark job

TestSparkMultiLayer.testStaticInvocation » Spark Job aborted due to stage fail...

**Comment by agibsonccc** [comment]
I pushed it up. Feel free to pull and let me know how it goes.

**Comment by agibsonccc** [comment]
Travis build is passing now save the little thing I just pushed up a fix
for wrt the new nlp modules:
https://travis-ci.org/SkymindIO/deeplearning4j

**Comment by smarthi** [comment]
Well ur fix is same as what I had, I would have beaten u to it if I didn't have to step out to run an errand, darn!! :)

**Comment by smarthi** [comment]
Fixed by PR# 140
