### ISSUE TITLE
Word2Vec Example

### ISSUE THREAD

**Issue by dav009** [SkymindIO/deeplearning4j#142]
I;m trying to get a very simple sample generating word2vec to work.

I've tried many versions of nd4j and dl4j.
My last attempt uses: `jblas 1.2.3`, `deeplearning4j  0.0.3.2.5`, 'nd4j-jblas 0.0.3.5.5-SNAPSHOT'

However I'm getting the following issue:

```
o.d.b.v.BaseTextVectorizer - Done working
o.d.b.v.BaseTextVectorizer - Invoking finish on index
o.d.m.w.Word2Vec - Building binary tree
o.d.m.w.Word2Vec - Constructing priority queue
o.d.m.w.Word2Vec - Built tree
o.d.m.w.Word2Vec - Resetting weights
Exception in thread "main" java.lang.AbstractMethodError: org.nd4j.linalg.factory.BaseNDArrayFactory.create(Lorg/nd4j/linalg/api/buffer/DataBuffer;[I[II)Lorg/nd4j/linalg/api/ndarray/INDArray;
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1394)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1500)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.rand(BaseNDArrayFactory.java:573)
	at org.nd4j.linalg.factory.Nd4j.rand(Nd4j.java:1241)
	at org.deeplearning4j.models.word2vec.wordstore.inmemory.InMemoryLookupCache.resetWeights(InMemoryLookupCache.java:357)
	at org.deeplearning4j.models.word2vec.Word2Vec.resetWeights(Word2Vec.java:528)
	at org.deeplearning4j.models.word2vec.Word2Vec.setup(Word2Vec.java:406)
	at org.deeplearning4j.models.word2vec.Word2Vec.buildVocab(Word2Vec.java:432)
	at org.deeplearning4j.models.word2vec.Word2Vec.fit(Word2Vec.java:258)
	at WordVectorGenerator.<init>(GenerateVector.scala:62)
	at GenerateVector$.main(GenerateVector.scala:32)
	at GenerateVector.main(GenerateVector.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by agibsonccc** [comment]
Use 0.0.3.2.7
